### ISSUE TITLE
Segmentation fault on Quick test

### ISSUE THREAD

**Issue by ryanESX** [berndpfrommer/tagslam_root#17]
I want to use ` roslaunch tagslam tagslam.launch bag:=`rospack find tagslam`/example/example.bag` to run. But  segfault
happened at startup. 
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeb5c9700 (LWP 171488)]
[New Thread 0x7fffeadc8700 (LWP 171489)]
[New Thread 0x7fffea5c7700 (LWP 171490)]
[New Thread 0x7fffe9dc6700 (LWP 171491)]
[ INFO] [1672392701.749175708]: optimizer mode: fast
[ INFO] [1672392701.749800840]: added body grasp_lab with 1 tags
[ INFO] [1672392701.749811416]: added body rig with 0 tags
[ INFO] [1672392701.750678155]: found 1 cameras
[ INFO] [1672392701.750933921]: camera cam0 has known pose!

Thread 1 "tagslam_node" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x41) at malloc.c:3102
3102    malloc.c: No such file or directory.
(gdb) 
(gdb) bt
#0  __GI___libc_free (mem=0x41) at malloc.c:3102
#1  0x00007ffff6e5b275 in gtsam::noiseModel::Gaussian::Covariance(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, bool) () from /usr/local/lib/libgtsam.so.4
#2  0x00007ffff7e7028c in tagslam::gtsam_utils::to_gtsam (pn=...)
    at /usr/include/eigen3/Eigen/src/Core/util/Meta.h:300
#3  0x00007ffff7ef4170 in tagslam::GTSAMOptimizer::addAbsolutePosePrior (
    this=0x555555cd7fa0, key=3, pwn=...)
    at /home/fboris/vslam_ws/tagslam_root/src/tagslam/include/tagslam/pose_with_noise.h:22
#4  0x00007ffff7f289e9 in tagslam::factor::AbsolutePosePrior::addToOptimizer (
    this=0x555555de6160, g=0x555555aa7790)
    at /home/fboris/vslam_ws/tagslam_root/src/tagslam/include/tagslam/factor/absolute_pose_prior.h:33
#5  0x00007ffff7e5d357 in tagslam::graph_utils::add_pose_maybe_with_prior (
    g=0x555555aa7790, t=..., name="cam:cam0", pwn=..., isCamPose=isCamPose@entry=true)
    at /home/fboris/vslam_ws/tagslam_root/src/tagslam/src/graph_utils.cpp:64
#6  0x00007ffff7e8ba82 in tagslam::TagSlam::readCameraPoses (this=0x7fffffffc250, 
    config=...) at /opt/ros/noetic/include/ros/time.h:181
#7  0x00007ffff7e8c7e7 in tagslam::TagSlam::initialize (this=0x7fffffffc250)
    at /opt/ros/noetic/include/xmlrpcpp/XmlRpcValue.h:73
#8  0x000055555555e11d in main (argc=<optimized out>, argv=<optimized out>)
    at /home/fboris/vslam_ws/tagslam_root/src/tagslam/src/tagslam_node.cpp:14
```
  
  
any idea of this issue? My GTSAM is 4.0.3. try both turn on and off with `-DGTSAM_USE_SYSTEM_EIGEN=ON` flag. My Eigen version in system is `3.3.7`

**Comment by berndpfrommer** [comment]
Typically this is due to the march=native compiler flag. Try compiling
gtsam and tagslam with the same settings.

**Comment by ryanESX** [comment]
You are correct. And I also found there are one more gtsam in my system cause CMake find wrong GTSAM lib.
